"""Centralized test fixtures for STRING-GSEA test suite."""

from pathlib import Path

import pytest

from string_gsea.configuration import GSEAConfig

# Base paths
TEST_DIR = Path(__file__).parent
DATA_DIR = TEST_DIR / "data"
DATASETS_DIR = DATA_DIR / "datasets"
FIXTURES_DIR = DATA_DIR / "fixtures"
ANNDATA_DIR = DATA_DIR / "h5ad"


def anndata_fixture_archives() -> list[Path]:
    """One DEA archive per prolfqua modelling facade.

    Generated by `scripts/generate_h5ad_fixtures.R`; each archive holds the
    `AnnData.h5ad` and the `.rnk` files prolfquapp derived from the same
    contrasts.
    """
    return sorted(ANNDATA_DIR.glob("*.zip"))


# ============================================================
# Dataset Fixtures (for Snakemake-compatible datasets)
# ============================================================


# ============================================================
# Input File Fixtures (backwards compatible)
# ============================================================


@pytest.fixture
def mouse_xlsx_zip() -> Path:
    """Mouse XLSX differential expression ZIP file."""
    return DATASETS_DIR / "mouse_xlsx" / "input.zip"


@pytest.fixture
def yeast_rnk_zip() -> Path:
    """Yeast RNK ZIP file."""
    return DATASETS_DIR / "yeast_rnk" / "input.zip"


# ============================================================
# Special Fixtures (test-specific, not for Snakemake)
# ============================================================


@pytest.fixture
def fasta_test_zip() -> Path:
    """FASTA test ZIP for species detection (no matching pattern)."""
    return FIXTURES_DIR / "no_matching_zip" / "fasta_test.zip"


@pytest.fixture
def dummy_session_rnk_zip() -> Path:
    """Dummy session RNK ZIP file."""
    return FIXTURES_DIR / "dummy_session" / "DEA_mouse_fasta_rnk.zip"


@pytest.fixture
def dummy_session_yml() -> Path:
    """Dummy session YAML file."""
    return FIXTURES_DIR / "dummy_session" / "session.yml"


@pytest.fixture
def multi_contrast_tsv_dir() -> Path:
    """Directory with multiple contrast TSV files."""
    return FIXTURES_DIR / "gsea_output"


@pytest.fixture
def single_contrast_tsv() -> Path:
    """Single-contrast STRING-DB GSEA TSV file for model tests."""
    return FIXTURES_DIR / "gsea_output" / "Bait_NCP_pUbT12_results.tsv"


@pytest.fixture
def gsea_config() -> GSEAConfig:
    """Minimal GSEAConfig for unit tests (no real API key)."""
    return GSEAConfig(
        api_key="test_key",
        fdr=0.25,
        ge_enrichment_rank_direction=1,
        caller_identity="test@example.com",
    )
